### PR TITLE
[WIP] Adding NFT Capability 

### LINKED ISSUE #34: Add NFT Capability to Edge Account-Based
Currently Native and Add Custom ERC20 tokens are available in the Edge environment.

For this bounty we're looking to add Native and Custom NFT (ERC721) viewing to this plugin. 

You should be able to 
> add custom nft contracts for viewing 
> transfer ownership of nfts 
> view metadata for nfts 
> if nfts allow for changing of metadata you should be able to do this also
> Bonus : ERC1155 (Enjin Protocol) Availability 

We're aware some of this would need UX flow.

We're looking to test this out in the HERC (https://github.com/hercone/herc-edge-login : stack-master branch) environment before merging the full flow into the full Edge app.

Finishing the plugin necessities in this bounty will unlock access to more bounties so do your best! 

Time frames are realistic but we would like something solid by late april.

Cheers
Logan
Cto
Herc.one

### PR DESCRIPTION
**Pull request by mul1sh**
This is a work in progress PR that fixes #34

### CODE REVIEW

**Comment by lrgeoemtry** [comment]
@mul1sh the checks have failed here, @paullinator this is for the NFTs in Edge can we get a medic?

**Comment by mul1sh** [comment]
@lrgeoemtry The build stalled for some reason, i think its an error in travis but if i push more changes, this will be fixed

**Comment by lrgeoemtry** [comment]
@mul1sh wheres this at? @johhonn might be able to take this over or maybe @julianapeace for that matter. please let us know, this is pertinent to our survival

**Comment by mul1sh** [comment]
@lrgeoemtry this was never completed because I never got the contracts in the mainnet on time. So yeah @johhonn or @julianapeace can definitely work on it, thanks

**Pull request closed without merging**
